#!/bin/sh

ssh chris@192.168.122.30 /bin/bash <<EOF
 cd ~/node-ci
 git pull
 npm install -production
 pm2 restart all
 exit
EOF
#!/bin/sh

ssh chris@192.168.122.40 /bin/bash <<EOF
 cd ~/node-ci
 git pull
 npm install -production
 pm2 restart all
 exit
EOF
